--- # Configure Selinux
- name: Enable selinux
  shell: setenforce 1
  tags: enable-selinux

- name: Configure selinux audit
  shell: grep "clamd" /var/log/audit.log | audit2allow -M clamd
  tags: selinux

- name: Configure selinux module
  shell: semodule -i clamd.pp
  tags: selinux
  notify:
  - Stop clamd service
  - Stop freshclam service
  - Stop selinux
  - Start and enable clamd service
  - Start freshclam service
  
- name: Execute freshclam
  shell: freshclam
  tags: exec-freshclam

...